### ISSUE TITLE
Fix code syntax highlighting

### ISSUE THREAD

**Issue by jbavari** [jbavari/jbavari.github.io#1]
Colors, links, javascript, html.

**Comment by jbavari** [comment]
Not sure why not working. Adjusted config as follows:

``` yml
# Site settings
title: Josh Bavari's Ramblings
email: jbavari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jbavari.github.io" # the base hostname & protocol for your site
twitter_username: jbavari
github_username:  jbavari

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
paginate: 5
gems: [jekyll-paginate]

```
